name: Archive machin-like.org

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-version-number:
    name: Check version number
    runs-on: ubuntu-22.04
    outputs:
      release: ${{ steps.version.outputs.release }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: actions/checkout@v4

      - name: Install PyGitHub
        run: python3 -m pip install PyGitHub

      - name: Check version number
        run: python3 .github/scripts/check_version_number.py ${{ secrets.GITHUB_TOKEN }} >> $GITHUB_OUTPUT
        id: version

  build-archive:
    name: Build archive
    runs-on: ubuntu-22.04
    needs:
      - check-version-number
    permissions:
      id-token: write
      contents: write
    if: needs.check-version-number.outputs.release != 'no'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: actions/checkout@v4

      - name: Clone arctans
        uses: actions/checkout@v4
        with:
          path: ./arctans
          repository: mscroggs/arctans
      - name: Install arctans
        run: |
          cd arctans
          python3 -m pip install .

      - run: python3 -m pip install .
      - run: python3 build.py _html --github-token ${{ secrets.GITHUB_TOKEN }}
        name: Build website HTML

      - name: Remove __pycache__
        run: |
          rm -r machin/__pycache__

      - name: Make lock file
        run: pip freeze > requirements.lock

      - name: Make tar.gz
        run: |
          tar \
          --exclude '.git' \
          --exclude 'arctans/.git' \
          --exclude 'arctans/arctans.egg-info' \
          --exclude 'arctans/build' \
          --exclude 'machin/__pycache__' \
          -czvf ../machin-like-v${{ needs.check-version-number.outputs.release }}.tar.gz .

      - name: Install PyGitHub
        run: python3 -m pip install PyGitHub
      - name: Make release
        run: python3 .github/scripts/make_release.py ../machin-like-v${{ needs.check-version-number.outputs.release }}.tar.gz ${{ needs.check-version-number.outputs.release }} ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Zenodo
        run: python3 .github/scripts/upload_to_zenodo ../machin-like-v${{ needs.check-version-number.outputs.release }}.tar.gz ${{ secrets.ZENODO_TOKEN }}
